### ISSUE TITLE
How to force at least 1 selected

### ISSUE THREAD

**Issue by javasol** [mapeveri/ionic-multiselect#11]
Hi,

Thanks for creating this! I have no idea why the creators of ionic haven't included a multi select in the default library. You would think it's a common enough request

I'm using form validation with ngMessages for all fields in a form. Would like to use form validation so that when the form is submitted it checks that at least 1 item in the multiselect is checked. Any way to do this?

Thank you

**Comment by mapeveri** [comment]
Hi @javasol unfortunately no, the operation is very simple, just select the items and returns the values that were selected. That's all what the library.
