### ISSUE TITLE
Setting the values on page load.

### ISSUE THREAD

**Issue by wyoumans** [mapeveri/ionic-multiselect#14]
Thanks for the plugin. Works pretty well.

I'm seeing that if the item has selected items on page load, they are not shown until after opening the selection window and touching the checkmark. Are you seeing this? Do I need to manually trigger the display of selected items somehow? The correct selected items are set in the selection window.

Here's a little video demo: https://www.dropbox.com/s/wf746qi385mliva/multiselect-initial-value.mp4?dl=0

**Comment by mariokreeft** [comment]
Did you find a workaround until fixed? Having the same issue and looks like i have to find an other plugin.. bummer.. Liked it till that point, too bad I did not find out earlier (same goes for you I guess)

**Comment by wyoumans** [comment]
@mariokreeft 

I did. I ended up overriding the template, hiding the selected options and just showing them myself above the multi select field. Works well until this is fixed.

**Comment by mariokreeft** [comment]
Thanks, will do the same.

**Comment by mariokreeft** [comment]
I did fix it, just added 1 line to the library, the one with value:
   ```
   //Attributes
      scope: {
        items: "=", // Needs to have a values
        value: "=", // Needs to have a value
        valueChangedCallback: "&valueChanged", // The callback used to signal that the value has changed
        getCustomTextCallback: "&getCustomText" // The callback used to get custom text based on the selected value
      },
```

In the html assign this to your own array:
```
                <multiselect 
                             header-text="Uitgevoerde acties:"
                             items="ms_data"
                             value="myvalue"

```
And in the controller initialize with (array of) selected values:

`        $scope.myvalue = ["181901"];


Cheers

**Comment by wyoumans** [comment]
@mariokreeft I just submitted my fix in a PR. Slightly different than yours. Seems pointless to require a value array passed in when we are already specifying checked values in the items array. The real problem here is that the checked values were being validated before the items array actually had any values (in my case fetched over an API). So this change adds a $watcher for items to revalidate the checked values any time the items array changes.
