### ISSUE TITLE
Problem when the user clear the selected items

### ISSUE THREAD

**Issue by ismaelgasparin** [mapeveri/ionic-multiselect#4]
Hello.

There is a problem when the user clear the items that were selected earlier: does not display the value of the text property, as is shown when no item is selected.

Solution: In scope.getText method, insert the following code:

```
if (!text.length) {
    // Set text default
    text = scope.defaultText;
}
```

Best regards

**Comment by mapeveri** [comment]
@ismaelgasparin Thanks, already released version 0.0.8
