### ISSUE TITLE
Expression 'undefined' in attribute 'value' used with directive 'multiselect' is non-assignable!

### ISSUE THREAD

**Issue by Purus** [mapeveri/ionic-multiselect#5]
I am using the mentioned here and it shows the selection list. But when I click on the final selection tick image, I get the stated error.

```
            <multiselect header-text="Select Categories" 
            items="categories" 
            text-property="categoryName"
             value-property="categoryKey" 
             text="Select categories" 
             note-text="Mandatory" 
             modal-template-url="js/templates/modal-template.html"
            template-url="js/templates/item-template.html" 
            value-changed="onValueChanged(value)"
              </multiselect>
```

Issue log is below.

```
ionic.bundle.js:26771 Error: [$compile:nonassign] Expression 'undefined' in attribute 'value' used with directive 'multiselect' is non-assignable!
http://errors.angularjs.org/1.5.3/$compile/nonassign?p0=undefined&p1=value&p2=multiselect
    at ionic.bundle.js:13415
    at parentSet (ionic.bundle.js:23031)
    at parentValueWatch (ionic.bundle.js:23044)
    at regularInterceptedExpression (ionic.bundle.js:28766)
    at Scope.$digest (ionic.bundle.js:30207)
    at Scope.$apply (ionic.bundle.js:30480)
    at HTMLButtonElement.<anonymous> (ionic.bundle.js:65289)
    at defaultHandlerWrapper (ionic.bundle.js:16764)
    at HTMLButtonElement.eventHandler (ionic.bundle.js:16752)
    at triggerMouseEvent (ionic.bundle.js:2953)
```

**Comment by mapeveri** [comment]
Hi @Purus you can give me one gist with all code html and your module js for a test.

**Comment by Purus** [comment]
@mapeveri I tried creating a fiddle bu could not make it successful.

I am using the plain example as shown in the repo.

**Comment by mapeveri** [comment]
@Purus here https://gist.github.com/

I need to see your code to help you. That works for me correctly

**Comment by Purus** [comment]
Thanks for your time on this.

Please find gist here.. https://gist.github.com/Purus/7adbbb6e94e7f61d62d95788b01b41e7

Kindly let me know if you need any other information.

**Comment by mapeveri** [comment]
@Purus Perfect, give me a few hours that I look and I commented the results :)

**Comment by mapeveri** [comment]
@Purus I just made a general test with your gist and works well. The only difference is that I put the property **items** harcoded .

Two comment only:
1. Check that the service returns an array of objects as follows: [{id: 1, value: "Item 1"}, {id: 2, value: "Item 2"}, {id: 3, value: "Item 3"}]
2. Check that the array properties of objects are the same as:

text-property="value" 
value-property="id"

**Comment by Purus** [comment]
The selection list appears fine and and to select the values. The issue
shows up in console only after clicking the tick symbol.

If the array is incorrect I believe the selection list should not appear.

Please correct me if I am wrong.

**Comment by mapeveri** [comment]
@Purus It may be, but I'm not sure.

These properties are correct?

text-property="value" 
value-property="id"

Give me one example of your array $scope.categories please.

**Comment by Purus** [comment]
This is one object of the array..

$hashKey:"object:118"
checked:false
id : "Animals"
value:"animals"
**proto** : Object

**Comment by mapeveri** [comment]
Please, give me array complete, i want make test with your data array. Thanks!

**Comment by Purus** [comment]
[{"id":"Animals","value":"animals","checked":false},{"id":"Birds","value":"birds","checked":false},{"id":"Dots & Lines","value":"dotlines","checked":false},{"id":"Festive - Diwali","value":"diwali","checked":false},{"id":"Festive - Onam","value":"onam","checked":false},{"id":"Festive - Pongal","value":"pongal","checked":false},{"id":"Flowers Based","value":"flowers","checked":false},{"id":"Freehand","value":"freehand","checked":false},{"id":"Gods","value":"gods","checked":false},{"id":"New Year","value":"newyear","checked":false},{"id":"Wedding","value":"wedding","checked":false}]

**Comment by mapeveri** [comment]
Very strange, with your data the example walks me well. After, I make test with angular 1.5.

Be sure to put the correct properties here:

text-property="categoryName"
value-property="categoryKey"

**Comment by Purus** [comment]
I have tried in several ways and could not make it work. If there are some ways to share my entire project for your reference, I can share the simple project.

**Comment by mapeveri** [comment]
Ok, it's a good idea

2016-05-17 12:48 GMT-03:00 Purusothaman Ramanujam notifications@github.com
:

**Comment by Purus** [comment]
Can you let me know your email address? Or you can drop a note to purushoth.r@gmail.com

**Comment by mapeveri** [comment]
My email is martinpeveri@gmail.com :)

2016-05-17 13:04 GMT-03:00 Purusothaman Ramanujam notifications@github.com
:

**Comment by mapeveri** [comment]
@Purus update the package last version please. 

I made some changes and release a new version by bower.

**Comment by mapeveri** [comment]
Update templates and javascript.

**Comment by Purus** [comment]
Now it works. 
But how do I get the key values of the selected items. I want the values to be obtained instead of the visible text.

**Comment by Purus** [comment]
Any help please..

**Comment by mapeveri** [comment]
Sorry, Tomorrow I see this issue.

**Comment by Purus** [comment]
Thanks. Plz let me know if you need any other help to test.

**Comment by mapeveri** [comment]
@Purus update ionic-multiselect to last version. Now you can get a array objects with items selected in your function onValueChanged in the controller.

**Comment by Purus** [comment]
Works as expected. Thanks a lot for your time.
