### ISSUE TITLE
How to display pre-selected values

### ISSUE THREAD

**Issue by PurpleEdge2214** [mapeveri/ionic-multiselect#6]
Can you explain how to display pre-selected values?

e.g. my data object has two values that are checked, but the initial display is empty until I open and close the modal.

`$scope.categoryData = [
            {  id: 1, value: "PHP", checked: false  },
            { id: 2, value: "Android", checked: true }, 
            { id: 3, value: "Wordpress", checked: true }
        ];
`
How do I get "Android, Wordpress" to display when the page first opens?

Thanks, I like the way this plugin works and I am looking forward to using it.

**Comment by mapeveri** [comment]
@PurpleEdge2214 What version do you have?

**Comment by PurpleEdge2214** [comment]
Hi, thanks for your help!

I can use the latest version. I am probably using it wrongly. I'll explain what I would LIKE to do.

I have a REST feed that has 900+ possible options, in the above format. If a user selects 3 of those 900 I would like to save only those 3 options and their values, in local storage, but synchronise those values whenever the Select modal is loaded, so my selected values are Checked.

So, save and display "Android, Wordpress", and save ["2","3"]

i.e. I need a function to return the selected values and text that I can save..
$scope.myCategories.text = ["Android",'Wordpress"];
$scope.myCategories.values = ["2","3"];

I don't want to save ["","2","3","","","","" etc, "900"], and I don't particularly want to save the entire 900 possible "data" options, because I usually won't select more than 2, or 3, and the possible options are dynamically updated, from time to time, from the REST feed.

And, I want to display "Android, Wordpress" whenever I like.

**Comment by PurpleEdge2214** [comment]
I've discovered that ...

`text="{{saved.categories}}"`

...displays the values I have saved in local storage.

I've noticed that ...

`is-translate="true"`

...breaks the latest version of multiselect.

I think I can figure out how to do what I need. When a new selection is made, I'll loop through the updated data, extract the IDs that are checked and save those to an array. When loading the data array I can look for matching IDs in my saved array and mark those options as "Checked" in my data array. That way I only need to save the "Checked" options.

**Comment by PurpleEdge2214** [comment]
I've discovered that ...

text="{{saved.categories}}"

...displays the values I have saved in local storage.

However, if I use a variable for "text=" then the variable can never get reset back to a default value when there are no options selected!

**Comment by PurpleEdge2214** [comment]
OK, got it working, using a variable for "text={{jobsFilter.categories}}"...

> ```
>     $scope.onValueChanged = function(value){
>         $scope.jobsFilter.categoryIDs = [];     // reset the saved IDs to ""
>         angular.forEach($scope.categoryData, function(item, key) {          // the updated list of categories with selected options "checked"
>             if (item.checked !== undefined && item.checked === true) {
>                 $scope.jobsFilter.categoryIDs.push(item.id);
>             }
>         });
>         $scope.jobsFilter.categories = ($scope.jobsFilter.categoryIDs.length <= 0) ? "Select job categories" : value;  // list of selected values as a string
>         FilterService.save($scope.jobsFilter);
>     };        
> ```

**Comment by mapeveri** [comment]
@PurpleEdge2214 I apologize at this time do not have much time to see this issue. If you can send a PR would be great. But I then see the problems.

Thanks!!

**Comment by mapeveri** [comment]
@PurpleEdge2214 A new version for get the selected records in an array of objects.

**Comment by PurpleEdge2214** [comment]
Thanks for that!

I've re-written the plugin for my use, and will upload a fork if I can figure out how to do that.

**Comment by mapeveri** [comment]
@PurpleEdge2214 Great.
