### ISSUE TITLE
How can I work with ng-model and clear component after submit?

### ISSUE THREAD

**Issue by fabionpinheiro** [mapeveri/ionic-multiselect#8]
Hi,
I have a form in my app and after submit, all fields are cleared, execpet te ionic-multiselect.
Is this possible? 

thanks!

**Comment by mapeveri** [comment]
@fabionpinheiro Hi, not is posible. What occurs to me is that after doing submit redirects to another URL.

With $state.go.

If you are not serving what I say and you want, you can send a PR.

Regards!

**Comment by fabionpinheiro** [comment]
@mapeveri Hi,

In my case, I clean all fields and get the same URL.
I think in a simple new method [clearList] or something similar. 

for now, adjusted as follows:
/\* 1 - mark as unchecked all itens */
for(i = 0; i < $scope.optionList.length; i++) {
  $scope.optionList[i].checked = false;
}

/\* 2 - rebuild the conponent */
document.getElementById('multiOprions').innerText = "";
$compile(document.getElementById('multiInformacoes') )($scope);

Regards!

**Comment by mapeveri** [comment]
@fabionpinheiro  Hi, I agree with what you say.

With one new method clearList, it will work well.
